services:
  - type: web
    name: crypto-trading-bot
    runtime: python
    pythonVersion: "3.10"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools==68.0.0
      pip install wheel
      pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: COINEX_ACCESS_ID
        value: your_coinex_access_id
      - key: COINEX_SECRET_KEY
        value: your_coinex_secret_key
      - key: TELEGRAM_TOKEN
        value: your_telegram_token
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id
